name: Social AddThis
package-name: aldryn-social-addthis
url: https://github.com/aldryn/aldryn-social-addthis
author:
  name: Divio AG
  url: https://www.divio.ch
installed-apps:
  - filer
  - easy_thumbnails
  - social_tags
  - aldryn_social_addthis
version: 0.1.3
description: Share CMS content via social media. 
license:
  name: BSD
  text: !literal-include LICENSE.txt
